using Microsoft.Extensions.DependencyInjection;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Media;
using Windows.UI;
using Pigeon_Uno.ViewModels;
using Pigeon_Uno.Core.Models;
using Pigeon_Uno.Core.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using Pigeon_Uno.Helpers;
using Pigeon_Uno.Services;
using Microsoft.UI.Xaml.Shapes;
using System.Collections.Specialized;
using Pigeon_Uno.Controls;

namespace Pigeon_Uno.Views;

public sealed partial class MapPage : Page
{
    public MapViewModel ViewModel { get; }
    private bool _isFollowingVehicle = false;
    private DateTime _lastVehiclePositionUiUpdate = DateTime.MinValue;
    private const int VehiclePositionUpdateIntervalMs = 200;
    private (double Lat, double Lon)? _lastRenderedVehiclePosition;
    private List<(double Lat, double Lon)> _undoStack = new();
    private List<(double Lat, double Lon)> _redoStack = new();
    private bool _isWPDockHidden = true;
    private readonly ObservabilityService? _observabilityService;
    private bool _isInitialized;
    private NotifyCollectionChangedEventHandler? _waypointsCollectionChangedHandler;

    // Manual field declarations for elements not generated by Uno XAML compiler
    private Border? geofencePointsBorder => FindName("geofence_points_border") as Border;
    private Button? btnCompleteGeofence => FindName("btn_complete_geofence") as Button;
    private TextBlock? geofenceStatusText => FindName("geofence_status_text") as TextBlock;
    private Border? geofenceStatusBorder => FindName("geofence_status_border") as Border;
    private ToggleButton? btnGeofenceMode => FindName("btn_geofence_mode") as ToggleButton;
    private Button? btnSendGeofence => FindName("btn_send_geofence") as Button;
    private Button? btnClearGeofence => FindName("btn_clear_geofence") as Button;
    private TextBlock? tbTotalDistance => FindName("tb_total_distance") as TextBlock;
    private ItemsControl? geofencePointsList => FindName("geofence_points_list") as ItemsControl;
    private TextBox? tbGeofenceRadius => FindName("tb_geofence_radius") as TextBox;
    private TextBox? tbGeofenceAltitude => FindName("tb_geofence_altitude") as TextBox;
    private ComboBox? cbGeofenceType => FindName("cb_geofence_type") as ComboBox;
    private StackPanel? wpDockStack => FindName("wp_dock_stack") as StackPanel;
    private Border? wpDock => FindName("wp_dock") as Border;
    private Button? wpDockButton => FindName("wp_dock_btn") as Button;
    private Border? followVehicleBorder => FindName("follow_wahana_border") as Border;
    private Border? geofencePanel => FindName("geofence_panel") as Border;
    private TextBox? tbGeofenceLat => FindName("tb_geofence_lat") as TextBox;
    private TextBox? tbGeofenceLon => FindName("tb_geofence_lon") as TextBox;
    private TextBlock? txtGeofenceCenter => FindName("txt_geofence_center") as TextBlock;
    private TextBlock? txtGeofenceArea => FindName("txt_geofence_area") as TextBlock;
    private Border? wpListPanel => FindName("wp_list_panel") as Border;
    private TextBlock? wpEmptyMessage => FindName("wp_empty_message") as TextBlock;
    private TextBlock? tbMarkersCount => FindName("tb_markers_count") as TextBlock;
    private Ellipse? geofenceStatusDot => FindName("geofence_status_dot") as Ellipse;
    private ToggleButton? btnSingleTapWP => FindName("btn_single_tap_wp") as ToggleButton;
    private bool _isSingleTapWaypointMode = false;

    public MapPage()
    {
        ViewModel = App.GetService<MapViewModel>();
        DataContext = ViewModel;

        this.InitializeComponent();
        _observabilityService = App.Current.Services.GetService<ObservabilityService>();

        Loaded += MapPage_Loaded;
        Unloaded += MapPage_Unloaded;
        SizeChanged += MapPage_SizeChanged;
    }

    protected override void OnNavigatedTo(Microsoft.UI.Xaml.Navigation.NavigationEventArgs e)
    {
        base.OnNavigatedTo(e);
        // Pastikan map di-refresh saat navigasi (termasuk dari page cache)
        RefreshMapView();
    }

    private void RefreshMapView()
    {
        _ = DispatcherQueue.TryEnqueue(Microsoft.UI.Dispatching.DispatcherQueuePriority.Low, () =>
        {
            try
            {
                mapControl.SetCenter(-7.2754, 112.7947, 15);
                RebuildWaypointDock();
                UpdateWaypointsOnMap();
            }
            catch (Exception ex)
            {
                Serilog.Log.Warning(ex, "[MapPage] RefreshMapView failed");
            }
        });
    }

    /// <summary>
    /// Dipanggil dari MainPage saat halaman ini diaktifkan kembali dari cache
    /// </summary>
    public void OnPageActivated()
    {
        Serilog.Log.Information("[MapPage] OnPageActivated called");
        RefreshMapView();
    }

    private void MapPage_Loaded(object sender, RoutedEventArgs e)
    {
        ApplyTabletLayout(ActualWidth);

        // Subscribe events hanya sekali
        if (!_isInitialized)
        {
            _isInitialized = true;

            if (ViewModel != null)
            {
                ViewModel.PropertyChanged += ViewModel_PropertyChanged;
                _waypointsCollectionChangedHandler ??= (_, __) => RebuildWaypointDock();
                ViewModel.Waypoints.CollectionChanged += _waypointsCollectionChangedHandler;
            }

            mapControl.WaypointMoved += MapControl_WaypointMoved;
            mapControl.GeofenceCenterMoved += MapControl_GeofenceCenterMoved;
            mapControl.GeofenceVertexMoved += MapControl_GeofenceVertexMoved;

            // Initialize offline map service
            try
            {
                var offlineService = App.Current.Services.GetService<IOfflineMapService>();
                if (offlineService != null)
                {
                    mapControl.SetOfflineMapService(offlineService);
                }
            }
            catch (Exception ex)
            {
                Serilog.Log.Warning(ex, "[MapPage] Failed to initialize offline map service");
            }
        }

        // Inisialisasi tampilan map selalu dijalankan setiap kali halaman ditampilkan
        _ = DispatcherQueue.TryEnqueue(Microsoft.UI.Dispatching.DispatcherQueuePriority.Low, () =>
        {
            mapControl.SetCenter(-7.2754, 112.7947, 15);

            if (wpListPanel != null)
            {
                wpListPanel.Visibility = Visibility.Collapsed;
            }

            if (tbMarkersCount != null) tbMarkersCount.Text = $"Markers: {ViewModel?.Waypoints.Count ?? 0} ▲";
            if (wpEmptyMessage != null)
            {
                wpEmptyMessage.Visibility = ViewModel?.Waypoints.Count == 0 ? Visibility.Visible : Visibility.Collapsed;
            }

            _isWPDockHidden = true;
            RebuildWaypointDock();
            UpdateWaypointsOnMap();
        });
    }

    private void MapPage_Unloaded(object sender, RoutedEventArgs e)
    {
        if (ViewModel != null)
        {
            ViewModel.PropertyChanged -= ViewModel_PropertyChanged;
            if (_waypointsCollectionChangedHandler != null)
            {
                ViewModel.Waypoints.CollectionChanged -= _waypointsCollectionChangedHandler;
            }
        }

        mapControl.WaypointMoved -= MapControl_WaypointMoved;
        mapControl.GeofenceCenterMoved -= MapControl_GeofenceCenterMoved;
        mapControl.GeofenceVertexMoved -= MapControl_GeofenceVertexMoved;

        _isInitialized = false;
    }

    private void MapPage_SizeChanged(object sender, SizeChangedEventArgs e)
    {
        ApplyTabletLayout(e.NewSize.Width);
    }

    private void ApplyTabletLayout(double width)
    {
        if (width <= 0)
        {
            return;
        }

        var compact = width < 820;
        MapToolbar.Spacing = compact ? 6 : 10;

        if (wpListPanel != null)
        {
            wpListPanel.MinWidth = compact ? 240 : 260;
            wpListPanel.MaxHeight = compact ? 220 : 260;
            wpListPanel.Padding = compact ? new Thickness(10) : new Thickness(12);
        }

        if (geofencePanel != null)
        {
            geofencePanel.MinWidth = compact ? 280 : 300;
            geofencePanel.MaxWidth = compact ? 300 : 340;
            geofencePanel.Margin = compact ? new Thickness(10) : new Thickness(20);
        }

        if (FindName("download_panel") is Border downloadPanel)
        {
            downloadPanel.MaxWidth = compact ? 320 : 360;
            downloadPanel.Padding = compact ? new Thickness(10) : new Thickness(12);
        }
    }

    private void ViewModel_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(ViewModel.VehiclePosition))
        {
            var vehiclePosition = ViewModel.VehiclePosition;
            if (vehiclePosition != null)
            {
                var now = DateTime.UtcNow;
                var lat = vehiclePosition.Latitude;
                var lon = vehiclePosition.Longitude;

                if ((now - _lastVehiclePositionUiUpdate).TotalMilliseconds < VehiclePositionUpdateIntervalMs)
                {
                    return;
                }

                if (_lastRenderedVehiclePosition.HasValue)
                {
                    var previous = _lastRenderedVehiclePosition.Value;
                    if (Math.Abs(previous.Lat - lat) < 1e-6 && Math.Abs(previous.Lon - lon) < 1e-6)
                    {
                        return;
                    }
                }

                DispatcherQueue.TryEnqueue(() =>
                {
                    mapControl.UpdateVehiclePosition(lat, lon);
                    _observabilityService?.Track("map.vehicle.render");

                    // Auto-follow if enabled
                    if (_isFollowingVehicle)
                    {
                        mapControl.SetCenter(lat, lon);
                    }
                });

                _lastVehiclePositionUiUpdate = now;
                _lastRenderedVehiclePosition = (lat, lon);
            }
        }
        else if (e.PropertyName == nameof(ViewModel.TotalDistance))
        {
            DispatcherQueue.TryEnqueue(() =>
            {
                // Sinkronkan label total jarak dengan ViewModel
                tbTotalDistance.Text = $"{ViewModel.TotalDistance:F2} km";
            });
        }
    }

    private void MapControl_DoubleTapped(object sender, Microsoft.UI.Xaml.Input.DoubleTappedRoutedEventArgs e)
    {
        // Get actual click position on map
        var clickPosition = e.GetPosition(mapControl);
        var (clickLat, clickLon) = mapControl.GetLatLonFromClick(clickPosition);
        
        Serilog.Log.Information("[MapPage] Double-click at screen position ({X}, {Y}) = Lat: {Lat}, Lon: {Lon}", 
            clickPosition.X, clickPosition.Y, clickLat, clickLon);
        
        // Check if in geofence drawing mode
        if (ViewModel.IsDrawingGeofence)
        {
            if (ViewModel.GeofenceType == Pigeon_Uno.Core.Models.GeofenceType.Polygon)
            {
                // Add geofence vertex at clicked position
                if (ViewModel.AddGeofenceVertexCommand.CanExecute((clickLat, clickLon)))
                {
                    ViewModel.AddGeofenceVertexCommand.Execute((clickLat, clickLon));
                    UpdateGeofenceVerticesList();
                    UpdateGeofenceOnMap();
                }
            }
            else if (ViewModel.GeofenceType == Pigeon_Uno.Core.Models.GeofenceType.Circular)
            {
                // Set geofence center at clicked position
                if (ViewModel.SetGeofenceCenterCommand.CanExecute((clickLat, clickLon)))
                {
                    ViewModel.SetGeofenceCenterCommand.Execute((clickLat, clickLon));
                    
                    // Update UI textboxes
                    if (tbGeofenceLat != null) tbGeofenceLat.Text = clickLat.ToString("F6");
                    if (tbGeofenceLon != null) tbGeofenceLon.Text = clickLon.ToString("F6");
                    
                    // Update geofence on map
                    UpdateGeofenceOnMap();
                    
                    // Update geofence info display
                    UpdateGeofenceInfo();
                    
                    // Enable send button
                    if (btnSendGeofence != null) btnSendGeofence.IsEnabled = true;
                    if (btnClearGeofence != null) btnClearGeofence.IsEnabled = true;
                    
                    // Update status
                    if (geofenceStatusText != null) geofenceStatusText.Text = "Geofence Active";
                    if (geofenceStatusDot != null) geofenceStatusDot.Fill = new SolidColorBrush(Color.FromArgb(0xFF, 0x10, 0xB9, 0x81)); // Success color
                    
                    Serilog.Log.Information("[MapPage] Geofence center set to Lat: {Lat}, Lon: {Lon}, Radius: {Radius}m", 
                        clickLat, clickLon, ViewModel.GeofenceRadius);
                }
            }
        }
        else
        {
            // Add Waypoint at clicked position
            if (ViewModel.AddWaypointCommand.CanExecute((clickLat, clickLon)))
            {
                ViewModel.AddWaypointCommand.Execute((clickLat, clickLon));
                _undoStack.Add((clickLat, clickLon));
                _redoStack.Clear();
                UpdateTotalDistance();
                UpdateWaypointsOnMap();
            }
        }
    }

    private void MapControl_Tapped(object sender, Microsoft.UI.Xaml.Input.TappedRoutedEventArgs e)
    {
        if (btnSingleTapWP?.IsChecked == true)
        {
            var position = e.GetPosition(mapControl);
            var (lat, lon) = mapControl.ScreenToLatLon(position.X, position.Y);
            
            if (ViewModel.AddWaypointCommand.CanExecute((lat, lon)))
            {
                ViewModel.AddWaypointCommand.Execute((lat, lon));
                _undoStack.Add((lat, lon));
                _redoStack.Clear();
                UpdateTotalDistance();
                UpdateWaypointsOnMap();
                
                Serilog.Log.Information("[MapPage] Waypoint added via single-tap at {Lat}, {Lon}", lat, lon);
            }
        }
    }

    private void ToggleSingleTapWP_Click(object sender, RoutedEventArgs e)
    {
        _isSingleTapWaypointMode = btnSingleTapWP?.IsChecked ?? false;
        Serilog.Log.Information("[MapPage] Single-tap waypoint mode: {State}", _isSingleTapWaypointMode);
    }

    private void ChooseMap(object sender, SelectionChangedEventArgs e)
    {
        if (sender is ComboBox comboBox && mapControl != null)
        {
            UpdateMapLayer(comboBox.SelectedIndex);
        }
    }

    private void UpdateMapLayer(int selectedIndex)
    {
        // Keep this mapping in sync with MapPage.xaml cb_map_type item order:
        // 0 ArcGIS Imagery, 1 OpenStreetMap, 2 Google Map, 3 Google Satellite
        var provider = selectedIndex switch
        {
            0 => SkiaMapControl.MapTileProvider.ArcGISImagery,
            1 => SkiaMapControl.MapTileProvider.OpenStreetMap,
            2 => SkiaMapControl.MapTileProvider.GoogleMap,
            3 => SkiaMapControl.MapTileProvider.GoogleSatellite,
            _ => SkiaMapControl.MapTileProvider.OpenStreetMap
        };
        
        mapControl.SetTileProvider(provider);
        
        Serilog.Log.Information("[MapPage] Map layer changed to: {Provider}", provider);
    }

    private void FollowVehicle_Click(object sender, RoutedEventArgs e)
    {
        _isFollowingVehicle = !_isFollowingVehicle;
        
        if (_isFollowingVehicle)
        {
            if (followVehicleBorder != null)
                followVehicleBorder.Background = new SolidColorBrush(Color.FromArgb(255, 0, 255, 0));
            
            if (ViewModel.VehiclePosition != null)
                CenterMapOnPosition(ViewModel.VehiclePosition.Latitude, ViewModel.VehiclePosition.Longitude);
        }
        else
        {
            if (followVehicleBorder != null)
                followVehicleBorder.Background = new SolidColorBrush(Color.FromArgb(0xFF, 0x53, 0xDF, 0xFA));
        }
    }

    private void CenterMapOnPosition(double latitude, double longitude)
    {
        mapControl.SetCenter(latitude, longitude);
    }

    private void SendWaypointCommand(object sender, RoutedEventArgs e)
    {
        if (ViewModel.Waypoints.Count == 0)
        {
            Serilog.Log.Warning("[MapPage] Send mission requested with no waypoints");
            return;
        }

        if (ViewModel.UploadMissionCommand.CanExecute(null))
        {
            ViewModel.UploadMissionCommand.Execute(null);
            Serilog.Log.Information("[MapPage] Send mission requested with {Count} waypoint(s)", ViewModel.Waypoints.Count);
        }
    }

    private void ToggleGeofencePanel_Click(object sender, RoutedEventArgs e)
    {
        if (geofencePanel == null) return;
        geofencePanel.Visibility = geofencePanel.Visibility == Visibility.Visible
            ? Visibility.Collapsed
            : Visibility.Visible;
    }

    private void SetGeofenceCenter_Click(object sender, RoutedEventArgs e)
    {
        if (tbGeofenceLat == null || tbGeofenceLon == null) return;
        if (double.TryParse(tbGeofenceLat.Text, out double lat) &&
            double.TryParse(tbGeofenceLon.Text, out double lon))
        {
            CenterMapOnPosition(lat, lon);
            if (ViewModel.SetGeofenceCenterCommand.CanExecute((lat, lon)))
            {
                ViewModel.SetGeofenceCenterCommand.Execute((lat, lon));
                UpdateGeofenceOnMap();
            }
        }
    }

    private void ToggleGeofenceMode_Click(object sender, RoutedEventArgs e)
    {
        if (btnGeofenceMode?.IsChecked == true)
        {
            ViewModel.StartDrawingGeofence();
            
            if (cbGeofenceType?.SelectedIndex == 0) // Circular
            {
                if (btnCompleteGeofence != null) btnCompleteGeofence.Visibility = Visibility.Collapsed;
                if (geofenceStatusText != null) geofenceStatusText.Text = "Geofence Active";
                if (geofenceStatusDot != null) geofenceStatusDot.Fill = new SolidColorBrush(Color.FromArgb(0xFF, 0x10, 0xB9, 0x81));
            }
            else // Polygon
            {
                if (btnCompleteGeofence != null) btnCompleteGeofence.Visibility = Visibility.Visible;
                if (geofenceStatusText != null) geofenceStatusText.Text = "Drawing";
                if (geofencePointsBorder != null) geofencePointsBorder.Visibility = Visibility.Visible;
            }
            
            if (geofenceStatusBorder != null)
                geofenceStatusBorder.Background = new SolidColorBrush(Color.FromArgb(0xFF, 0xFF, 0xA5, 0x00));
        }
        else
        {
            ViewModel.IsDrawingGeofence = false;
            if (btnCompleteGeofence != null) btnCompleteGeofence.Visibility = Visibility.Collapsed;
            if (geofenceStatusText != null) geofenceStatusText.Text = ViewModel.IsGeofenceActive ? "Geofence Active" : "Geofence Inactive";
            if (geofenceStatusDot != null) geofenceStatusDot.Fill = new SolidColorBrush(
                ViewModel.IsGeofenceActive ? Color.FromArgb(0xFF, 0x10, 0xB9, 0x81) : Color.FromArgb(0xFF, 0x6C, 0x75, 0x7D));
            if (geofenceStatusBorder != null)
                geofenceStatusBorder.Background = new SolidColorBrush(
                    ViewModel.IsGeofenceActive ? Color.FromArgb(0xFF, 0x28, 0xA7, 0x45) : Color.FromArgb(0xFF, 0x6C, 0x75, 0x7D));
        }
    }

    private void CompleteGeofence_Click(object sender, RoutedEventArgs e)
    {
        if (ViewModel.CompleteGeofenceCommand.CanExecute(null))
            ViewModel.CompleteGeofenceCommand.Execute(null);
        
        if (btnCompleteGeofence != null) btnCompleteGeofence.Visibility = Visibility.Collapsed;
        if (btnSendGeofence != null) btnSendGeofence.IsEnabled = true;
        if (btnClearGeofence != null) btnClearGeofence.IsEnabled = true;
        if (geofenceStatusText != null) geofenceStatusText.Text = "Geofence Active";
        if (geofenceStatusDot != null) geofenceStatusDot.Fill = new SolidColorBrush(Color.FromArgb(0xFF, 0x10, 0xB9, 0x81));
        if (geofenceStatusBorder != null)
            geofenceStatusBorder.Background = new SolidColorBrush(Color.FromArgb(0xFF, 0x28, 0xA7, 0x45));
        
        UpdateGeofenceOnMap();
    }

    private void SendGeofence_Click(object sender, RoutedEventArgs e)
    {
        if (ViewModel.SendGeofenceCommand.CanExecute(null))
            ViewModel.SendGeofenceCommand.Execute(null);
    }

    private void ClearGeofence_Click(object sender, RoutedEventArgs e)
    {
        if (ViewModel.ClearGeofenceCommand.CanExecute(null))
            ViewModel.ClearGeofenceCommand.Execute(null);
        
        if (btnSendGeofence != null) btnSendGeofence.IsEnabled = false;
        if (btnClearGeofence != null) btnClearGeofence.IsEnabled = false;
        if (geofencePointsBorder != null) geofencePointsBorder.Visibility = Visibility.Collapsed;
        if (geofenceStatusText != null) geofenceStatusText.Text = "Geofence Inactive";
        if (geofenceStatusDot != null) geofenceStatusDot.Fill = new SolidColorBrush(Color.FromArgb(0xFF, 0x6C, 0x75, 0x7D));
        if (geofenceStatusBorder != null)
            geofenceStatusBorder.Background = new SolidColorBrush(Color.FromArgb(0xFF, 0x6C, 0x75, 0x7D));
        
        mapControl.ClearGeofence();
    }

    private void Undo_Click(object sender, RoutedEventArgs e)
    {
        if (_undoStack.Count > 0 && ViewModel.Waypoints.Count > 0)
        {
            var lastWaypoint = _undoStack[_undoStack.Count - 1];
            _undoStack.RemoveAt(_undoStack.Count - 1);
            _redoStack.Add(lastWaypoint);
            
            var waypointToRemove = ViewModel.Waypoints[ViewModel.Waypoints.Count - 1];
            ViewModel.DeleteWaypointCommand.Execute(waypointToRemove);
            UpdateTotalDistance();
        }
    }

    private void Redo_Click(object sender, RoutedEventArgs e)
    {
        if (_redoStack.Count > 0)
        {
            var waypoint = _redoStack[_redoStack.Count - 1];
            _redoStack.RemoveAt(_redoStack.Count - 1);
            _undoStack.Add(waypoint);
            
            ViewModel.AddWaypointCommand.Execute((waypoint.Lat, waypoint.Lon));
            UpdateTotalDistance();
        }
    }

    private void ResetMarkers_Click(object sender, RoutedEventArgs e)
    {
        if (ViewModel.ClearMissionCommand.CanExecute(null))
        {
            ViewModel.ClearMissionCommand.Execute(null);
            _undoStack.Clear();
            _redoStack.Clear();
            UpdateTotalDistance();
        }
    }

    private void ExportWaypoints_Click(object sender, RoutedEventArgs e)
    {
        if (ViewModel.SaveMissionCommand.CanExecute(null))
        {
            ViewModel.SaveMissionCommand.Execute(null);
        }
    }

    private void ImportWaypoints_Click(object sender, RoutedEventArgs e)
    {
        if (ViewModel.LoadMissionCommand.CanExecute(null))
        {
            ViewModel.LoadMissionCommand.Execute(null);
            UpdateTotalDistance();
        }
    }

    private void UpdateTotalDistance()
    {
        if (ViewModel.Waypoints.Count < 2)
        {
            tbTotalDistance.Text = "0.00 km";
            return;
        }

        double totalDistance = 0;
        for (int i = 0; i < ViewModel.Waypoints.Count - 1; i++)
        {
            var wp1 = ViewModel.Waypoints[i];
            var wp2 = ViewModel.Waypoints[i + 1];
            totalDistance += GeoMath.CalculateDistance(
                wp1.Latitude, wp1.Longitude,
                wp2.Latitude, wp2.Longitude);
        }

        tbTotalDistance.Text = $"{(totalDistance / 1000):F2} km";
    }

    private void UpdateGeofenceVerticesList()
    {
        if (geofencePointsList == null) return;
        geofencePointsList.ItemsSource = null;
        geofencePointsList.ItemsSource = ViewModel.GeofenceVertices;
    }

    private void UpdateGeofenceParameters()
    {
        if (tbGeofenceRadius != null && double.TryParse(tbGeofenceRadius.Text, out double radius))
            ViewModel.SetGeofenceRadius(radius);

        if (tbGeofenceAltitude != null && double.TryParse(tbGeofenceAltitude.Text, out double altitude))
            ViewModel.SetGeofenceMaxAltitude(altitude);

        var selectedType = (cbGeofenceType?.SelectedIndex ?? 0) == 0
            ? Pigeon_Uno.Core.Models.GeofenceType.Circular
            : Pigeon_Uno.Core.Models.GeofenceType.Polygon;
        
        if (selectedType != ViewModel.GeofenceType)
        {
            ViewModel.SetGeofenceType(selectedType);
            if (geofencePointsBorder != null)
                geofencePointsBorder.Visibility = selectedType == Pigeon_Uno.Core.Models.GeofenceType.Polygon
                    ? Visibility.Visible : Visibility.Collapsed;
        }
    }

    private void GeofenceType_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (ViewModel == null) return;
        
        var selectedType = (cbGeofenceType?.SelectedIndex ?? 0) == 0
            ? Pigeon_Uno.Core.Models.GeofenceType.Circular 
            : Pigeon_Uno.Core.Models.GeofenceType.Polygon;
        
        ViewModel.SetGeofenceType(selectedType);
        
        // Show/hide polygon points list
        if (geofencePointsBorder != null)
            geofencePointsBorder.Visibility = selectedType == Pigeon_Uno.Core.Models.GeofenceType.Polygon
                ? Visibility.Visible : Visibility.Collapsed;
        
        // Clear existing geofence when type changes
        mapControl.ClearGeofence();
        
        // Reset status
        if (geofenceStatusText != null) geofenceStatusText.Text = "Geofence Inactive";
        if (geofenceStatusDot != null) geofenceStatusDot.Fill = new SolidColorBrush(Color.FromArgb(0xFF, 0x6C, 0x75, 0x7D));
        if (geofenceStatusBorder != null)
            geofenceStatusBorder.Background = new SolidColorBrush(Color.FromArgb(0xFF, 0x6C, 0x75, 0x7D));
        if (btnSendGeofence != null) btnSendGeofence.IsEnabled = false;
        if (btnClearGeofence != null) btnClearGeofence.IsEnabled = false;
    }

    private void GeofenceRadius_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (ViewModel == null || tbGeofenceRadius == null) return;
        
        if (double.TryParse(tbGeofenceRadius.Text, out double radius))
        {
            ViewModel.SetGeofenceRadius(radius);
            if (ViewModel.IsGeofenceActive && ViewModel.GeofenceType == Pigeon_Uno.Core.Models.GeofenceType.Circular)
            {
                UpdateGeofenceOnMap();
                UpdateGeofenceInfo();
            }
        }
    }

    private void GeofenceAltitude_TextChanged(object sender, TextChangedEventArgs e)
    {
        if (ViewModel == null || tbGeofenceAltitude == null) return;
        if (double.TryParse(tbGeofenceAltitude.Text, out double altitude))
            ViewModel.SetGeofenceMaxAltitude(altitude);
    }

    private void ToggleWPDock(object sender, RoutedEventArgs e)
    {
        if (wpListPanel == null) return;
        if (wpListPanel.Visibility == Visibility.Collapsed)
        {
            wpListPanel.Visibility = Visibility.Visible;
            if (tbMarkersCount != null) tbMarkersCount.Text = $"Markers: {ViewModel.Waypoints.Count} ▼";
            if (wpEmptyMessage != null) wpEmptyMessage.Visibility = Visibility.Collapsed;
        }
        else
        {
            wpListPanel.Visibility = Visibility.Collapsed;
            if (tbMarkersCount != null) tbMarkersCount.Text = $"Markers: {ViewModel.Waypoints.Count} ▲";
            if (wpEmptyMessage != null) wpEmptyMessage.Visibility = ViewModel.Waypoints.Count == 0 ? Visibility.Visible : Visibility.Collapsed;
        }
    }

    private void RebuildWaypointDock()
    {
        if (ViewModel == null || wpDockStack == null) return;

        wpDockStack.Children.Clear();
        
        // Update empty message visibility
        if (wpEmptyMessage != null)
        {
            wpEmptyMessage.Visibility = ViewModel.Waypoints.Count == 0 ? Visibility.Visible : Visibility.Collapsed;
        }
        
        // Add waypoint items
        foreach (var wp in ViewModel.Waypoints.OrderBy(w => w.Sequence))
        {
            var item = new WaypointItem(wp);
            wpDockStack.Children.Add(item);
        }

        if (tbMarkersCount != null)
        {
            tbMarkersCount.Text = $"Markers: {ViewModel.Waypoints.Count} {(wpListPanel?.Visibility == Visibility.Visible ? "▼" : "▲")}";
        }

        UpdateTotalDistance();
    }

    private void DeleteWaypoint_Click(object sender, RoutedEventArgs e)
    {
        if (sender is Button button && button.DataContext is WaypointData waypoint)
        {
            if (ViewModel.DeleteWaypointCommand.CanExecute(waypoint))
            {
                ViewModel.DeleteWaypointCommand.Execute(waypoint);
                UpdateWaypointsOnMap();
            }
        }
    }

    /// <summary>
    /// Update waypoint markers on map
    /// </summary>
    private void UpdateWaypointsOnMap()
    {
        if (mapControl == null) return;

        // Clear existing waypoints
        mapControl.ClearWaypoints();

        // Add all waypoints to map
        foreach (var wp in ViewModel.Waypoints.OrderBy(w => w.Sequence))
        {
            mapControl.AddWaypointMarker(
                wp.Sequence,
                wp.Latitude,
                wp.Longitude,
                wp.Altitude,
                wp.Command.ToString()
            );
        }
    }

    /// <summary>
    /// Update geofence on map
    /// </summary>
    private void UpdateGeofenceOnMap()
    {
        if (mapControl == null || !ViewModel.IsGeofenceActive) return;

        if (ViewModel.GeofenceType == Pigeon_Uno.Core.Models.GeofenceType.Circular)
        {
            mapControl.SetGeofence(
                true,
                ViewModel.GeofenceCenterLat,
                ViewModel.GeofenceCenterLon,
                ViewModel.GeofenceRadius,
                null
            );
            
            // Update geofence info display
            UpdateGeofenceInfo();
        }
        else if (ViewModel.GeofenceVertices.Count >= 3)
        {
            var vertices = ViewModel.GeofenceVertices
                .Select(v => (v.Lat, v.Lon))
                .ToList();
            
            mapControl.SetGeofence(
                false,
                0, 0, 0,
                vertices
            );
            
            // Update geofence info display
            UpdateGeofenceInfo();
        }
    }

    /// <summary>
    /// Update geofence info display
    /// </summary>
    private void UpdateGeofenceInfo()
    {
        Serilog.Log.Debug("[MapPage] UpdateGeofenceInfo called - txtCenter: {Center}, txtArea: {Area}", 
            txtGeofenceCenter != null, txtGeofenceArea != null);
        
        if (txtGeofenceCenter == null || txtGeofenceArea == null)
        {
            Serilog.Log.Debug("[MapPage] Geofence info TextBlocks not found");
            return;
        }

        if (ViewModel.GeofenceType == Pigeon_Uno.Core.Models.GeofenceType.Circular)
        {
            // Update center info
            txtGeofenceCenter.Text = $"{ViewModel.GeofenceCenterLat:F6}, {ViewModel.GeofenceCenterLon:F6}";
            
            // Calculate and display area (πr²)
            double areaM2 = Math.PI * ViewModel.GeofenceRadius * ViewModel.GeofenceRadius;
            double areaKm2 = areaM2 / 1_000_000;
            txtGeofenceArea.Text = areaKm2 < 1 
                ? $"{areaM2:F0} m²" 
                : $"{areaKm2:F3} km²";
            
            Serilog.Log.Debug("[MapPage] Geofence info updated - Center: {Center}, Area: {Area}", 
                txtGeofenceCenter.Text, txtGeofenceArea.Text);
        }
        else if (ViewModel.GeofenceVertices.Count >= 3)
        {
            // Update vertices count
            txtGeofenceCenter.Text = $"{ViewModel.GeofenceVertices.Count} vertices";
            
            // Calculate polygon area (Shoelace formula)
            double area = CalculatePolygonArea(ViewModel.GeofenceVertices);
            double areaKm2 = area / 1_000_000;
            txtGeofenceArea.Text = areaKm2 < 1 
                ? $"{area:F0} m²" 
                : $"{areaKm2:F3} km²";
            
            Serilog.Log.Debug("[MapPage] Geofence polygon info updated - Vertices: {Count}, Area: {Area}", 
                ViewModel.GeofenceVertices.Count, txtGeofenceArea.Text);
        }
    }

    /// <summary>
    /// Calculate polygon area using Shoelace formula
    /// </summary>
    private double CalculatePolygonArea(System.Collections.ObjectModel.ObservableCollection<Pigeon_Uno.Core.Models.GeofenceVertex> vertices)
    {
        if (vertices.Count < 3) return 0;

        double area = 0;
        for (int i = 0; i < vertices.Count; i++)
        {
            int j = (i + 1) % vertices.Count;
            area += vertices[i].Lon * vertices[j].Lat;
            area -= vertices[j].Lon * vertices[i].Lat;
        }
        area = Math.Abs(area) / 2.0;
        
        // Convert from degrees² to meters² (approximate at equator)
        // 1 degree ≈ 111,320 meters
        area *= 111320.0 * 111320.0;
        
        return area;
    }

    /// <summary>
    /// Handle waypoint moved event from map control
    /// </summary>
    private void MapControl_WaypointMoved(object sender, SkiaMapControl.WaypointMovedEventArgs e)
    {
        // Find waypoint in ViewModel and update position
        var waypoint = ViewModel.Waypoints.FirstOrDefault(w => w.Sequence == e.Sequence);
        if (waypoint != null)
        {
            waypoint.Latitude = e.NewLat;
            waypoint.Longitude = e.NewLon;
            
            // Update total distance
            UpdateTotalDistance();
            
            Serilog.Log.Debug("[MapPage] Waypoint {Seq} updated to {Lat}, {Lon}", 
                e.Sequence, e.NewLat, e.NewLon);
        }
    }

    /// <summary>
    /// Handle geofence center moved event from map control
    /// </summary>
    private void MapControl_GeofenceCenterMoved(object sender, SkiaMapControl.GeofenceCenterMovedEventArgs e)
    {
        // Update ViewModel geofence center
        if (ViewModel.SetGeofenceCenterCommand.CanExecute((e.NewLat, e.NewLon)))
        {
            ViewModel.SetGeofenceCenterCommand.Execute((e.NewLat, e.NewLon));
            
            // Update UI textboxes
            tbGeofenceLat.Text = e.NewLat.ToString("F6");
            tbGeofenceLon.Text = e.NewLon.ToString("F6");
            
            // Update geofence info
            UpdateGeofenceInfo();
            
            Serilog.Log.Debug("[MapPage] Geofence center updated to {Lat}, {Lon}", 
                e.NewLat, e.NewLon);
        }
    }

    /// <summary>
    /// Handle geofence vertex moved event from map control
    /// </summary>
    private void MapControl_GeofenceVertexMoved(object sender, SkiaMapControl.GeofenceVertexMovedEventArgs e)
    {
        // Update ViewModel geofence vertex
        if (e.VertexIndex >= 0 && e.VertexIndex < ViewModel.GeofenceVertices.Count)
        {
            var vertex = ViewModel.GeofenceVertices[e.VertexIndex];
            vertex.Lat = e.NewLat;
            vertex.Lon = e.NewLon;
            
            // Update geofence info (area calculation)
            UpdateGeofenceInfo();
            
            Serilog.Log.Debug("[MapPage] Geofence vertex {Index} updated to {Lat}, {Lon}", 
                e.VertexIndex, e.NewLat, e.NewLon);
        }
    }

    // Offline Maps Panel Methods
    private void ShowDownloadPanel_Click(object sender, RoutedEventArgs e)
    {
        var downloadPanel = (Border)FindName("download_panel");
        if (downloadPanel != null)
        {
            downloadPanel.Visibility = Visibility.Visible;
        }
    }

    private void HideDownloadPanel_Click(object sender, RoutedEventArgs e)
    {
        var downloadPanel = (Border)FindName("download_panel");
        if (downloadPanel != null)
        {
            downloadPanel.Visibility = Visibility.Collapsed;
        }
    }
}
